import { createAction } from '@reduxjs/toolkit';
import * as ACTION_TYPES from '../ActionTypes/Status';

export const updateDataInput = createAction(ACTION_TYPES.UPDATE_INPUT_DATA)
export const updateDataEdit = createAction(ACTION_TYPES.UPDATE_EDIT_DATA)
export const setModalAddStatus = createAction(ACTION_TYPES.SET_ADD_STATUS)
// export const openModalAddStatus = createAction(ACTION_TYPES.OPEN_ADD_STATUS)
// export const closeModalAddStatus = createAction(ACTION_TYPES.CLOSE_ADD_STATUS)
export const createStatus = createAction(ACTION_TYPES.CREATE_STATUS)
export const createStatusSuccess = createAction(ACTION_TYPES.CREATE_STATUS_SUCCESS)
export const createStatusFail = createAction(ACTION_TYPES.CREATE_STATUS_FAIL)
export const editStatus = createAction(ACTION_TYPES.EDIT_STATUS)
export const editStatusSuccess = createAction(ACTION_TYPES.EDIT_STATUS_SUCCESS)
export const editStatusFail = createAction(ACTION_TYPES.EDIT_STATUS_FAIL)
export const searchStatusBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_BY_SOCKET)
export const searchStatusSuccessBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_SUCCESS_BY_SOCKET)
export const searchStatusFailBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_FAIL_BY_SOCKET)
export const deleteStatus = createAction(ACTION_TYPES.DELETE_STATUS)
export const deleteStatusSuccess = createAction(ACTION_TYPES.DELETE_STATUS_SUCCESS)
export const deleteStatusFail = createAction(ACTION_TYPES.DELETE_STATUS_FAIL)
export const openConfirmDelete= createAction(ACTION_TYPES.OPEN_CONFIRM_DELETE)
export const closeConfirmDelete = createAction(ACTION_TYPES.CLOSE_CONFIRM_DELETE)
export const openConfirmEdit = createAction(ACTION_TYPES.OPEN_CONFIRM_EDIT)
export const closeConfirmEdit = createAction(ACTION_TYPES.CLOSE_CONFIRM_EDIT)
export const resetData = createAction(ACTION_TYPES.RESSET_DATA)
export const searchAndPaginationData = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION)
export const searchAndPaginationDataSuccess = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION_SUCCESS)
export const searchAndPaginationDataFailed = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION_FAILED)
export const updatePagination = createAction(ACTION_TYPES.UPDATE_PAGINATION)