import { createAction } from '@reduxjs/toolkit';
import * as ACTION_TYPES from '../ActionTypes/UserRole';

// export const updateDataInput = createAction(ACTION_TYPES.UPDATE_INPUT_DATA_STATUS)
// export const updateDataEdit = createAction(ACTION_TYPES.UPDATE_EDIT_DATA_STATUS)
export const setModalAdd = createAction(ACTION_TYPES.SET_OPNEN_ADD_USERROLE)
export const create = createAction(ACTION_TYPES.CREATE_USERROLE)
export const createSuccess = createAction(ACTION_TYPES.CREATE_USERROLE_SUCCESS)
export const createFail = createAction(ACTION_TYPES.CREATE_USERROLE_FAIL)
// export const edit = createAction(ACTION_TYPES.EDIT_STATUS)
// export const editSuccess = createAction(ACTION_TYPES.EDIT_STATUS_SUCCESS)
// export const editFail = createAction(ACTION_TYPES.EDIT_STATUS_FAIL)
// export const searchBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_BY_SOCKET)
// export const searchSuccessBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_SUCCESS_BY_SOCKET)
// export const searchFailBySocket = createAction(ACTION_TYPES.SEARCH_STATUS_FAIL_BY_SOCKET)
// export const deleteData = createAction(ACTION_TYPES.DELETE_STATUS)
// export const deleteDataSuccess = createAction(ACTION_TYPES.DELETE_STATUS_SUCCESS)
// export const deleteDataFail = createAction(ACTION_TYPES.DELETE_STATUS_FAIL)
// export const openConfirmDelete= createAction(ACTION_TYPES.OPEN_CONFIRM_DELETE_STATUS)
// export const closeConfirmDelete = createAction(ACTION_TYPES.CLOSE_CONFIRM_DELETE_STATUS)
// export const openConfirmEdit = createAction(ACTION_TYPES.OPEN_CONFIRM_EDIT_STATUS)
// export const closeConfirmEdit = createAction(ACTION_TYPES.CLOSE_CONFIRM_EDIT_STATUS)
// export const resetData = createAction(ACTION_TYPES.RESSET_DATA_STATUS)
// export const searchAndPaginationData = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION_STATUS)
// export const searchAndPaginationDataSuccess = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION_STATUS_SUCCESS)
// export const searchAndPaginationDataFailed = createAction(ACTION_TYPES.SEARCH_AND_PAGINATION_STATUS_FAILED)
// export const updatePagination = createAction(ACTION_TYPES.UPDATE_PAGINATION_STATUS)
