// --------------- LOGIN---------------------//
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_GOOGLE = 'LOGIN_GOOGLE';
export const LOGIN_TRANDITION = 'LOGIN_TRANDITION';
export const LOGIN_TRANDITION_SUCCESS = 'LOGIN_TRANDITION_SUCCESS';
export const LOGIN_TRANDITION_FAIL = 'LOGIN_TRANDITION_FAIL';

// ---------------REGISTER---------------------//
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

// --------------- FORGOT PASSWORD---------------------//
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

// --------------- CHANGE PASSWORD---------------------//
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// --------------- USER---------------------//
export const CHECK_AUTHORIZATION = 'CHECK_AUTHORIZATION';
export const CHECK_AUTHORIZATION_SUCCESS = 'CHECK_AUTHORIZATION_SUCCESS';

// --------------- LOADING---------------------//
export const LOADING = 'LOADING';
export const CLOSE_LOADING = 'CLOSE_LOADING';



// --------------- MAIN GROUP---------------------//
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA';
export const OPEN_ADD_MAINGOURP = 'OPEN_ADD_MAINGOURP';
export const CLOSE_ADD_MAINGOURP = 'CLOSE_ADD_MAINGOURP';
export const CREATE_MAIN_GROUP = 'CREATE_MAIN_GROUP';
export const CREATE_MAIN_GROUP_SUCCESS = 'CREATE_MAIN_GROUP_SUCCESS';
export const CREATE_MAIN_GROUP_FAIL = 'CREATE_MAIN_GROUP_FAIL';
export const SEARCH_MAIN_GROUP_BY_SOCKET = 'SEARCH_MAIN_GROUP_BY_SOCKET';
export const SEARCH_MAIN_GROUP_SUCCESS_BY_SOCKET = 'SEARCH_MAIN_GROUP_SUCCESS_BY_SOCKET';
export const SEARCH_MAIN_GROUP_FAIL_BY_SOCKET = 'SEARCH_MAIN_GROUP_FAIL_BY_SOCKET';
export const DELETE_MAIN_GROUP = 'DELETE_MAIN_GROUP';
export const DELETE_MAIN_GROUP_SUCCESS = 'DELETE_MAIN_GROUP_SUCCESS';
export const DELETE_MAIN_GROUP_FAIL = 'DELETE_MAIN_GROUP_FAIL';
export const OPEN_CONFIRM_DELETE = 'OPEN_CONFIRM_DELETE';
export const CLOSE_CONFIRM_DELETE = 'LOSE_CONFIRM_DELETE';
export const OPEN_CONFIRM_EDIT = 'OPEN_CONFIRM_EDIT';
export const CLOSE_CONFIRM_EDIT = 'LOSE_CONFIRM_EDIT';
export const RESSET_DATA = 'RESSET_DATA';
export const SEARCH_AND_PAGINATION = 'SEARCH_AND_PAGINATION';
export const SEARCH_AND_PAGINATION_SUCCESS = 'SEARCH_AND_PAGINATION_SUCCESS';
export const SEARCH_AND_PAGINATION_FAILED = 'SEARCH_AND_PAGINATION_FAILED';