export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_GOOGLE = 'LOGIN_GOOGLE';
export const LOGIN_TRANDITION = 'LOGIN_TRANDITION';
export const LOGIN_TRANDITION_SUCCESS = 'LOGIN_TRANDITION_SUCCESS';
export const LOGIN_TRANDITION_FAIL = 'LOGIN_TRANDITION_FAIL';